### ISSUE TITLE
dotnet watch run mvc app will crash the Dispose method

### ISSUE THREAD

**Issue by q42jaap** [serilog/serilog-sinks-applicationinsights#46]
When I use `dotnet watch run` the Dispose method of `ApplicationInsightsSinkBase` has a null ref somewhere.
```
Now listening on: http://localhost:8080
Application started. Press Ctrl+C to shut down.
Application is shutting down...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSinkBase.Dispose(Boolean disposeManagedResources)
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSinkBase.Dispose()
   at Serilog.LoggerConfiguration.<CreateLogger>b__28_0()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MyApp.Program.Main(String[] args) in /Users/jaap/Projects/MyApp/Program.cs:line 12
watch : Exited
```

This crashes the program.

Program.cs contains this:
```
.WriteTo.ApplicationInsightsTraces(string.Empty))
```

**Comment by jbattermann** [comment]
This had been fixed with the latest commit and build/release ([v96](https://github.com/serilog/serilog-sinks-applicationinsights/releases/tag/v96)) however for some reason it's build/nuget-package number wasn't increased over [the one before](https://github.com/serilog/serilog-sinks-applicationinsights/releases/tag/v96) and therefore probably never pushed to nuget.org etc.

Hrmmm.. I'll try to find out / remember why this might be hapening but you could for the time being use the v96 release binaries and it should no longer occur.

**Comment by q42jaap** [comment]
I'm not sure how to manually use v96, but we'll just wait until 2.5.1 or 2.6 is out there. Thanks!

**Comment by jbattermann** [comment]
New package is up on nuget.org now!

**Comment by MichaCo** [comment]
Still getting a NullReference exception during `Dispose` during app shutdown (ASP.NET Core Service)

![image](https://user-images.githubusercontent.com/5837539/38416729-fa270aac-3995-11e8-8ddf-d4ef658d1377.png)

When debugging into it, I found that the TelemetryChannel is null and [`Flush`](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L589) is implemented pretty poorly without checking anything...

While running the app, the channel is set and everything works "normally". 
I guess its null because the app is shutting down...

**Comment by jbattermann** [comment]
Alright  - once the build is through and the updated package pushed, can you give it another try @MichaCo ? I obviously cannot fix AI's internals, but the IDisposable guidelines clearly state that .Dispose() methods may not throw exceptions.

Hence, if for some reason the .Flush() does not succeed, it is caught and (unfortunately) swallowed. What this means is that you can not really rely on an app shutdown triggered .Dispose() will result in all unflushed AI messages to end up in AI - so it might be good practice to do this explicitly in your app's (end of its) lifecycle to ensure all messages do end up over at AI.

**Comment by MichaCo** [comment]
@jbattermann I agree, that try/catch is ugly but there is nothing else you can do, so, its fine ;)

I can confirm that 2.6.0 is now working just fine.
Thanks for the quick fix!
